services:
  xss-validator:
    image: ghcr.io/bladewing/xss-validator:main
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./run.py:/app/run.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
